service: marketplace

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  getSeller:
    handler: handler.getAllSellers
    events:
      - http:
          path: sellers
          method: get
  createSeller:
    handler: handler.createSeller
    events:
      - http:
          path: seller
          method: post
