service: marketplace

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  getSeller:
    handler: handler.getAllSellers
    events:
      - http:
          path: sellers
          method: get
