service: marketplace

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  getSeller:
    handler: SellerHandler.getAllSellers
    events:
      - http:
          path: sellers
          method: get
  createSeller:
    handler: SellerHandler.createSeller
    events:
      - http:
          path: seller
          method: post
  updateSeller:
    handler: SellerHandler.updateSeller
    events:
      - http:
          path: seller/{id}
          method: put
  deleteSeller:
    handler: SellerHandler.deleteSeller
    events:
      - http:
          path: seller/{id}
          method: delete
